### ISSUE TITLE
Create Staging DB in Dev SQL server called FMS_Phase_II

### ISSUE THREAD

**Issue by tom-karasch** [gaepdit/FMS#312]
Phase II Staging DB that is clone of Dev FMS DB

```[tasklist]
### Tasks
```

**Comment by DeeptiPrattipati** [comment]
Step1: Took the FMS database backup from Dev SQL Server.
Step2: Save the login details because we can restore same access in new database.
Step3: Created new database called FMS_Phase_II and restored with the FMS data.
Step4: Provide the same access like FMS on this new database  FMS_Phase_II.

Tom: Please verify your access and let me know if you have any issue with connecting the new database FMS_Phase_II
